import { createListCollection } from "@ark-ui/react";

export const schoolList = [
    "Jaipur Public School",
    "Rajasthan International Academy",
    "St. Xavier's School Jaipur",
    "Delhi Public School Jaipur",
    "Maharaja Sawai Bhawani Singh School",
    "Subodh Public School Jaipur",
    "Maheshwari Public School",
    "Army Public School Jaipur",
    "Sanskar School Jaipur",
    "Bharatiya Vidya Bhavan Jaipur",
    "Cambridge Court High School",
    "St. Angela Sophia Senior Secondary School",
    "Modern Public School Kota",
    "Bright Future Academy Udaipur",
    "Heritage Girls School Ajmer",
    "Adarsh Vidya Mandir Jodhpur",
    "Gyan Vihar World School Jaipur",
    "Pink Pearl Public School Jaipur",
    "Rajmata Gayatri Devi Public School Jaipur",
    "Tagore International School Jaipur",
    "Springfield Public School Udaipur",
    "Rajasthan Central Academy Bikaner",
    "Sophia Senior Secondary School Ajmer",
    "St. Anselm's Pink City School Jaipur",
    "Global Public School Jaipur",
    "Vivekananda Global School",
    "Kendriya Vidyalaya No. 1 Jaipur",
    "Kendriya Vidyalaya No. 2 Jaipur",
    "DAV Centenary Public School Jaipur",
    "Ryan International School Jaipur",
    "Children’s Academy Jaipur",
    "Seedling Modern Public School Jaipur",
    "Alpha Beta School Jaipur",
    "The Palace School Jaipur",
    "Daffodils World School Jaipur",
    "Rainbow School Jaipur",
    "Sanskriti The School Jaipur",
    "Maharaja Agrasen Vidyalaya Jaipur",
    "Blue Bells Public School Jaipur",
    "Saint Soldier Public School Jaipur",
    "Step By Step High School Jaipur",
    "Oxford International Academy Jaipur",
    "Rukmani Birla Modern High School Jaipur",
    "Bright Minds Academy Jodhpur",
    "The Shri Ram Universal School Jaipur",
    "Shanti Asiatic School Jaipur",
    "Blooming Dales Public School Jaipur",
    "Spring Dale School Jaipur",
    "Bal Bharti Public School Jaipur",
    "Lotus Valley International School Jaipur",
    "Central Academy School Jaipur",
    "Prince Academy Sikar",
    "Mayoor School Ajmer",
    "Bishop's Academy Ajmer",
    "Greenfield International School Jaipur",
    "Pearls Academy Jaipur",
    "Sunshine Modern Public School Jaipur",
    "Jaipur Cambridge School",
    "Rays International School Jaipur",
    "The New Era School Jaipur",
    "Mount Litera Zee School Jaipur",
    "St. Wilfred's School Jaipur",
    "Holy Spirit School Jaipur",
    "Vidhyashram International School Jodhpur",
    "Silver Oak School Jaipur",
    "Gurukul International School Jaipur",
    "Shri Mahaveer Public School Jaipur",
    "Akashdeep Public School Jaipur",
    "Narayana E-Techno School Jaipur",
    "Lal Bahadur Shastri Senior Secondary School Jaipur",
    "Spring Blossom School Jaipur",
    "Saint Edmund’s School Jaipur",
    "Noble International Academy Jaipur",
    "Green Valley School Jaipur",
    "St. Mary's Convent Senior Secondary School Jaipur",
    "Alok Senior Secondary School Udaipur",
    "GD Goenka Public School Jaipur",
    "Harvest International School Jaipur",
    "Divine International School Jaipur",
    "Edify World School Jaipur",
    "Alpine Convent School Jaipur",
    "Galaxy Public School Jaipur",
    "St. John's International School Jaipur",
    "Jagriti Public School Jaipur",
    "Elite Academy Jaipur",
    "Samarth International School Jaipur",
    "Paramount Public School Jaipur",
    "Modern International School Jaipur",
    "Samyak Academy Jaipur",
    "Bright Future School Jaipur",
    "Vidya Niketan Jaipur",
    "Victory World School Jaipur",
    "Lords International School Jaipur",
    "Dream Valley International School Jaipur",
    "The Pinnacle School Jaipur",
    "Bright Star Academy Jaipur",
    "Jai Shree Public School Jaipur",
    "Radiant International Academy Jaipur",
    "Bal Bhavan Public School Jaipur",
    "Golden Era Public School Jaipur",
    "Silver Crest Academy Jaipur",
    "Sunrise International School Jaipur",
    "Angel High School Jaipur",
    "Blossom International School Jaipur",
    "Rajasthan Academy School Jaipur",
    "Evergreen Public School Jaipur",
    "Infinity Academy Jaipur",
    "Universal Academy Jaipur",
    "Saraswati Modern Public School Jaipur",
    "Future Stars Academy Jaipur",
    "Crescent International School Jaipur",
    "Morning Glory Academy Jaipur",
    "Pioneer International School Jaipur",
    "Excel Academy Jaipur",
    "Prestige International School Jaipur",
    "Rising Sun Academy Jaipur",
    "Shree Balaji Public School Jaipur",
    "Golden Bells Academy Jaipur",
    "Sacred Heart Public School Jaipur",
    "Vidyasagar Academy Jaipur",
    "Royal Academy Jaipur",
    "Shri Ram Public School Jaipur",
    "Bright Vision Academy Jaipur",
    "Sapphire Academy Jaipur",
    "Sunbeam Academy Jaipur",
    "Horizon Public School Jaipur",
    "Elite International Academy Jaipur",
    "Dreamland Public School Jaipur",
    "Crystal International School Jaipur",
    "Radiance Academy Jaipur",
    "Pearl Academy Jaipur",
    "Future Vision Academy Jaipur",
    "Excelence International School Jaipur",
    "Cosmos Public School Jaipur",
    "Supernova Academy Jaipur",
    "Harmony International School Jaipur",
    "Shri Krishna Academy Jaipur",
    "Dawn Academy Jaipur",
    "Silverline International School Jaipur",
    "Ideal Academy Jaipur",
    "New Horizon Academy Jaipur",
    "Starlight Academy Jaipur",
    "Golden Horizon Public School Jaipur",
    "Brilliance Academy Jaipur",
    "Eternal Light Public School Jaipur",
    "New Era Academy Jaipur",
    "Bright Horizon Public School Jaipur",
    "Galaxy Academy Jaipur",
    "New World Public School Jaipur",
    "Bright Path Academy Jaipur",
    "Modern Era School Jaipur",
    "Pinnacle Academy Jaipur",
    "Lighthouse Public School Jaipur",
    "Noble Vision Academy Jaipur",
    "Stellar Academy Jaipur",
    "True Light Academy Jaipur",
    "Silver Bells Academy Jaipur",
    "Zenith International School Jaipur",
    "True Horizon Academy Jaipur",
    "Shri Shakti Public School Jaipur",
    "Infinite Light Academy Jaipur",
    "True Star Academy Jaipur",
    "Emerald Academy Jaipur",
    "True Success Public School Jaipur",
    "Aspire International School Jaipur"
  ]
  
  export const schools = createListCollection({
    items: [
      
    ]
  });

  

  export interface ColourOption {
    readonly value: string;
    readonly label: string;
  }
  
  export const schoolL: readonly ColourOption[] = [
    { label: "Jaipur Public School", value: "Jaipur Public School" },
    { label: "Rajasthan International Academy", value: "Rajasthan International Academy" },
    { label: "St. Xavier's School Jaipur", value: "St. Xavier's School Jaipur" },
    { label: "Delhi Public School Jaipur", value: "Delhi Public School Jaipur" },
    { label: "Maharaja Sawai Bhawani Singh School", value: "Maharaja Sawai Bhawani Singh School" },
    { label: "Subodh Public School Jaipur", value: "Subodh Public School Jaipur" },
    { label: "Maheshwari Public School", value: "Maheshwari Public School" },
    { label: "Army Public School Jaipur", value: "Army Public School Jaipur" },
    { label: "Sanskar School Jaipur", value: "Sanskar School Jaipur" },
    { label: "The Shri Ram School Delhi", value: "The Shri Ram School Delhi" },
    { label: "Mother's International School Delhi", value: "Mother's International School Delhi" },
    { label: "Vasant Valley School Delhi", value: "Vasant Valley School Delhi" },
    { label: "Delhi Public School RK Puram", value: "Delhi Public School RK Puram" },
    { label: "Modern School Barakhamba Road Delhi", value: "Modern School Barakhamba Road Delhi" },
    { label: "National Public School Bangalore", value: "National Public School Bangalore" },
    { label: "Inventure Academy Bangalore", value: "Inventure Academy Bangalore" },
    { label: "Greenwood High International School Bangalore", value: "Greenwood High International School Bangalore" },
    { label: "Bishop Cotton Boys' School Bangalore", value: "Bishop Cotton Boys' School Bangalore" },
    { label: "Bishop Cotton Girls' School Bangalore", value: "Bishop Cotton Girls' School Bangalore" },
    { label: "Chettinad Vidyashram Chennai", value: "Chettinad Vidyashram Chennai" },
    { label: "Sishya School Chennai", value: "Sishya School Chennai" },
    { label: "DAV Boys Senior Secondary School Chennai", value: "DAV Boys Senior Secondary School Chennai" },
    { label: "DAV Girls Senior Secondary School Chennai", value: "DAV Girls Senior Secondary School Chennai" },
    { label: "PSBB Senior Secondary School Chennai", value: "PSBB Senior Secondary School Chennai" },
    { label: "St. Paul’s School Darjeeling", value: "St. Paul’s School Darjeeling" },
    { label: "The Doon School Dehradun", value: "The Doon School Dehradun" },
    { label: "Welham Girls' School Dehradun", value: "Welham Girls' School Dehradun" },
    { label: "Welham Boys' School Dehradun", value: "Welham Boys' School Dehradun" },
    { label: "St. Joseph’s Academy Dehradun", value: "St. Joseph’s Academy Dehradun" },
    { label: "La Martiniere Boys School Kolkata", value: "La Martiniere Boys School Kolkata" },
    { label: "La Martiniere Girls School Kolkata", value: "La Martiniere Girls School Kolkata" },
    { label: "Calcutta International School Kolkata", value: "Calcutta International School Kolkata" },
    { label: "Modern High School for Girls Kolkata", value: "Modern High School for Girls Kolkata" },
    { label: "Don Bosco School Kolkata", value: "Don Bosco School Kolkata" },
    { label: "St. Mary’s School Pune", value: "St. Mary’s School Pune" },
    { label: "Delhi Public School Pune", value: "Delhi Public School Pune" },
    { label: "Symbiosis International School Pune", value: "Symbiosis International School Pune" },
    { label: "Vidya Valley School Pune", value: "Vidya Valley School Pune" },
    { label: "Bishop’s Co-Ed School Pune", value: "Bishop’s Co-Ed School Pune" },
    { label: "St. Xavier's School Mumbai", value: "St. Xavier's School Mumbai" },
    { label: "Cathedral and John Connon School Mumbai", value: "Cathedral and John Connon School Mumbai" },
    { label: "Bombay Scottish School Mumbai", value: "Bombay Scottish School Mumbai" },
    { label: "Campion School Mumbai", value: "Campion School Mumbai" },
    { label: "Dhirubhai Ambani International School Mumbai", value: "Dhirubhai Ambani International School Mumbai" },
    { label: "Hyderabad Public School Hyderabad", value: "Hyderabad Public School Hyderabad" },
    { label: "International School of Hyderabad", value: "International School of Hyderabad" },
    { label: "Oakridge International School Hyderabad", value: "Oakridge International School Hyderabad" },
    { label: "Chirec International School Hyderabad", value: "Chirec International School Hyderabad" },
    { label: "Gitanjali School Hyderabad", value: "Gitanjali School Hyderabad" },
    { label: "Navrachana International School Vadodara", value: "Navrachana International School Vadodara" },
    { label: "Delhi Public School Ahmedabad", value: "Delhi Public School Ahmedabad" },
    { label: "Anand Niketan School Ahmedabad", value: "Anand Niketan School Ahmedabad" },
    { label: "Udgam School Ahmedabad", value: "Udgam School Ahmedabad" },
    { label: "Amity International School Noida", value: "Amity International School Noida" },
    { label: "Pathways World School Gurgaon", value: "Pathways World School Gurgaon" },
    { label: "Shiv Nadar School Gurgaon", value: "Shiv Nadar School Gurgaon" },
    { label: "Scottish High International School Gurgaon", value: "Scottish High International School Gurgaon" }
  ];
  